Exception on / [POST]
Traceback (most recent call last):
  File "C:\Users\miloslav\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\miloslav\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\miloslav\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\miloslav\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\miloslav\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\miloslav\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/miloslav/PycharmProjects/CYOA/app.py", line 34, in main
    print(request.json['message_id'])
KeyError: 'message_id'
